"""empty message

Revision ID: 1da512918700
Revises: 1f42bdab02ac
Create Date: 2015-12-10 14:10:51.993506

"""

# revision identifiers, used by Alembic.
revision = '1da512918700'
down_revision = '1f42bdab02ac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_list',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('content', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_list')
    ### end Alembic commands ###
