"""empty message

Revision ID: 1f42bdab02ac
Revises: 5a44e27d3488
Create Date: 2015-12-02 16:01:21.609121

"""

# revision identifiers, used by Alembic.
revision = '1f42bdab02ac'
down_revision = '5a44e27d3488'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('image_list', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slider')
    ### end Alembic commands ###
