"""empty message

Revision ID: 1f62cf8270a4
Revises: 405bac7222f0
Create Date: 2015-09-29 17:01:21.276749

"""

# revision identifiers, used by Alembic.
revision = '1f62cf8270a4'
down_revision = '405bac7222f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('publish', sa.Boolean(), nullable=True))
    op.drop_column('activity', 'status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('activity', 'publish')
    ### end Alembic commands ###
