"""empty message

Revision ID: 23fc76e750a0
Revises: 1da512918700
Create Date: 2015-12-14 11:08:07.737105

"""

# revision identifiers, used by Alembic.
revision = '23fc76e750a0'
down_revision = '1da512918700'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VIP',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('begin', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['youjiao_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VIP')
    ### end Alembic commands ###
