"""empty message

Revision ID: 25c124ce7011
Revises: 39ded2bff92b
Create Date: 2015-10-16 17:42:39.337097

"""

# revision identifiers, used by Alembic.
revision = '25c124ce7011'
down_revision = '39ded2bff92b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio', sa.Column('media_meta', postgresql.JSON(), nullable=True))
    op.add_column('audio', sa.Column('media_process', postgresql.JSON(), nullable=True))
    op.add_column('audio', sa.Column('name', sa.String(length=200), nullable=True))
    op.drop_column('audio', 'json')
    op.add_column('document', sa.Column('media_meta', postgresql.JSON(), nullable=True))
    op.add_column('document', sa.Column('media_process', postgresql.JSON(), nullable=True))
    op.add_column('document', sa.Column('name', sa.String(length=200), nullable=True))
    op.drop_column('document', 'json')
    op.add_column('video', sa.Column('media_meta', postgresql.JSON(), nullable=True))
    op.add_column('video', sa.Column('media_process', postgresql.JSON(), nullable=True))
    op.add_column('video', sa.Column('name', sa.String(length=200), nullable=True))
    op.drop_column('video', 'json')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('json', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('video', 'name')
    op.drop_column('video', 'media_process')
    op.drop_column('video', 'media_meta')
    op.add_column('document', sa.Column('json', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('document', 'name')
    op.drop_column('document', 'media_process')
    op.drop_column('document', 'media_meta')
    op.add_column('audio', sa.Column('json', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('audio', 'name')
    op.drop_column('audio', 'media_process')
    op.drop_column('audio', 'media_meta')
    ### end Alembic commands ###
