"""add leavemessage

Revision ID: 43021558ff36
Revises: 5576b81e725f
Create Date: 2016-01-04 16:32:30.661178

"""

# revision identifiers, used by Alembic.
revision = '43021558ff36'
down_revision = '5576b81e725f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['youjiao_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave_message')
    ### end Alembic commands ###
