"""empty message

Revision ID: 5a44e27d3488
Revises: 25c124ce7011
Create Date: 2015-12-02 11:42:19.386269

"""

# revision identifiers, used by Alembic.
revision = '5a44e27d3488'
down_revision = '25c124ce7011'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courseware', sa.Column('cover_img_url', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courseware', 'cover_img_url')
    ### end Alembic commands ###
